### ISSUE TITLE
Support VCF Writer

### ISSUE THREAD

**Issue by eaton-lab** [pmckenz1/ipcoal#16]
Use first sample as reference by default but optionally allow user to select an index.

```python
model.write_vcf(PATH, reference_index=0))
```

**Comment by eaton-lab** [comment]
Looks like a good start in the latest commit. Notes on additional ideas to implement:

1. allow selecting the reference (see above)
2. the sites that are written do not seem to all be variable
3. currently works with sim_loci but not sim_snps
4. report number of SNPs and linkage blocks written not loci/bp
5. allow returning as a DF if no filename provided. 
6. allow grouping samples into diploids randomly (seed) or by providing a dict.

**Comment by pmckenz1** [comment]
1) Thinking that this might be best to reference by sample name rather than index but can be convinced otherwise. **Done** this way, but simple to change.
2) Whoops, good catch. Indexing bug, **done** now. 
3) Ah yes. Think they should they all be #CHROM=0 for SNPs, with POS going up one by one? Or all separate CHROM with POS=1 for each?
4) **Done**.
5) **Done**, but -- good to keep these strictly in vcf format? String values in the cells? I guess it probably makes sense to have ints for #CHROM and POS, and for the genotypes.
6) Pending.

3 and 6 still left to take care of.

**Comment by eaton-lab** [comment]
Great!

3. It should be exactly like in the `.df` output of ipcoal. The CHROM is the locus idx and the POS is the position. Except they should be 1-indexed in the VCF instead of 0-indexed. So in `sim_snps` they should all have POS=1, and all be different CHROM.

**Comment by pmckenz1** [comment]
Makes sense -- on it.

**Comment by eaton-lab** [comment]
I think the VCF writer may warrant its own class object.

**Comment by eaton-lab** [comment]
I agree about just using strings in the dataframe cells. It is possible to make more complex dtypes to represent `0/0` vs `0/1` genotypes in a dataframe, like in scikit-allel, but I definitely do not want scikit-allel as a dependency. It's really burdensome. So in that sense maybe the dataframe result is not super useful and we should just focus on making a good VCF file.

**Comment by eaton-lab** [comment]
New features checked:
1. Defaults to using the *known* ancestral sequence as reference.
2. Works with loci or SNPs
3. allow returning as a DF
4. more verbose info in VCF header (e.g., loci lengths)
5. allow grouping samples as diploids (in VCF and other writing functions).

I pushed an update as v.0.1.3.
